('100m','Athletisme','solo'),ok
('200m','Athletisme','solo'), ok
('400m','Athletisme','solo'),
('Aviron','Aviron','multi'),
('Badminton','Badminton','multi'),
('Basket-ball','Basket-ball','multi'),
('Boxe','Boxe','solo'),
('Canoe-kayak course','Canoe-kayak','multi'),
('Canoe-kayak slalom','Canoe-kayak',''),
('Cyclisme','Cyclisme','solo'),
('Cyclisme VTT','Cyclisme','solo'),
('Cyclisme BMX','Cyclisme','solo'),
('Cyclisme Piste','Cyclisme','solo'),
('Equitation Saut','Equitation','solo'),
('Equitation Dressage','Equitation','solo'),
('Equitation Concours','Equitation','solo'),
('Escrime','Escrime','solo'),
('Football','Football','multi'),
('Golf','Golf','solo'),
('Gymnastique artistique','Gymnastique','solo'),
('Gymnastique trampoline','Gymnastique','solo'),
('Gymnastique rythmique','Gymnastique','solo'),
('Halterophilie','Halterophilie','solo'),
('Handball','Handball','multi'),
('Hockey sur gazon','Hockey sur gazon','multi'),
('Judo','Judo','solo'),
('Lutte','Lutte','solo'),
('200m','Natation','solo'),
('Plongeon','Natation','solo'),
('Pentathlon moderne','Pentathlon moderne','solo'),
('Rugby a sept','Rugby a sept','multi'),
('Taekwondo','Taekwondo','solo'),
('Tennis','Tennis','solo'),
('Tennis equipe','Tennis','multi'),
('Tennis de table','Tennis de table','solo'),
('Tennis de table equipe','Tennis de table','multi'),
('Tir','Tir','solo'),
('Carabine','Tir','solo'),
('Pistolet','Tir','solo'),
('Tir a larc','Tir a larc','solo'),
('Triathlon','Triathlon','solo'),
('Voile','Voile','solo'),
('Volley-ball','Volley-ball','multi');
('Beach-volley','Volley-ball','multi');
